---
- name: test ping
  hosts: all
  become: yes
  tasks:
  - name: ping server task
    ping:
  - name: copy html file to client server
    file:
     src: /home/loshakigor/ansible/index.html
     dest: /tmp
     owner: loshakigor
