# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias dai='docker rmi $(docker images)'
alias dac='docker container rm -f $(docker container ls -q)'
alias sc='docker container ls -a'
alias si='docker images '
