project = "infra-271615"
disk_image = "centos-7-v20200309"
ssh_key = "c:\\source\\infra\\key\\loshakigor.pub"
host = "serv"
filelist="C:/source/infra/ansible/server/config/"
private_ssh_key="C:/source/infra/key/id_rsa"
